CREATE TABLE `bills` (
  `guid` varchar(36) NOT NULL,
  `bill_year` int(11) DEFAULT NULL,
  `session` varchar(10) DEFAULT NULL,
  `bill_number` varchar(10) DEFAULT NULL,
  `short_title` text DEFAULT NULL,
  `general_provisions` text DEFAULT NULL,
  `highlighted_provisions` text DEFAULT NULL,
  `subjects` text DEFAULT NULL,
  `code_sections` text DEFAULT NULL,
  `appropriations` text DEFAULT NULL,
  `last_action` text DEFAULT NULL,
  `last_action_owner` text DEFAULT NULL,
  `last_action_date` datetime DEFAULT NULL,
  `bill_link` text DEFAULT NULL,
  `sponsor` varchar(255) DEFAULT NULL,
  `floor_sponsor` varchar(255) DEFAULT NULL,
  `ai_analysis` text DEFAULT NULL,
  `ai_impact_rating` int(11) DEFAULT 0,
  `ai_impact_rating_explanation` text DEFAULT NULL,
  `level` int(11) DEFAULT 0,
  `position` int(11) DEFAULT 0,
  PRIMARY KEY (`guid`),
  UNIQUE KEY `guid_UNIQUE` (`guid`),
  KEY `idx_bill_year_session` (`bill_year`,`session`),
  KEY `idx_bill_number` (`bill_number`),
  KEY `idx_sponsor` (`sponsor`),
  KEY `idx_floor_sponsor` (`floor_sponsor`),
  KEY `idx_last_action_date` (`last_action_date`),
  FULLTEXT KEY `idx_subjects` (`subjects`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
